version: '3.8'

services:
  ml-api:
    build: 
      context: ../../
      dockerfile: src/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount model file if you want to update it without rebuilding
      - ../../model.pkl:/app/model.pkl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MLflow tracking server
  mlflow:
    image: python:3.12-slim
    ports:
      - "5000:5000"
    volumes:
      - ../../mlruns:/mlruns
    working_dir: /app
    command: >
      bash -c "pip install mlflow &&
               mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns"
    restart: unless-stopped

networks:
  default:
    name: mlops-network