name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # change if your main branch has a different name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies and generate model
      - name: Validate and Generate ML Model
        run: |
          chmod +x scripts/validate-pipeline.sh
          ./scripts/validate-pipeline.sh
        env:
          # Skip MLflow logging in CI
          MLFLOW_TRACKING_URI: ""

      # 4. Log in to DockerHub (you need to add secrets)
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build and push image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-water-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlops-water-api:${{ github.sha }}
